import prisma from "../lib/prisma";

/**
 * Category hierarchy exported from database
 * Auto-generated from export-categories.ts
 *
 * Note: Duplicate names (e.g., "Jazz" under both Figure Skating and Aerial)
 * are intentional and will be created as separate records in the database,
 * each with its own ID and parentId reference to their respective parent.
 */
const categories = [
  {
    name: "Home",
    position: 0,
    description: null,
    children: [],
  },
  {
    name: "Dance wear",
    position: 1,
    description: null,
    children: [
      {
        name: "Aerial",
        position: 0,
        description: null,
        children: [
          { name: "Accessories", description: null, position: 0, children: [] },
          { name: "Acro", description: null, position: 1, children: [] },
          { name: "Airbrush", description: null, position: 2, children: [] },
          { name: "Character inspired", description: null, position: 3, children: [] },
          { name: "Gallery", description: null, position: 4, children: [] },
          { name: "Hand painted", description: null, position: 5, children: [] },
          { name: "Jazz", description: null, position: 6, children: [] },
          { name: "Lyrical", description: null, position: 7, children: [] },
          { name: "Modern", description: null, position: 8, children: [] },
          { name: "Other", description: null, position: 9, children: [] },
          { name: "Pancake tutus", description: null, position: 10, children: [] },
          { name: "Stretch", description: null, position: 11, children: [] },
          { name: "Tap", description: null, position: 12, children: [] },
        ],
      },
      {
        name: "Figure Skating",
        description: null,
        position: 1,
        children: [
          { name: "Accessories", description: null, position: 0, children: [] },
          { name: "Acro", description: null, position: 1, children: [] },
          { name: "Airbrush", description: null, position: 2, children: [] },
          { name: "Character inspired", description: null, position: 3, children: [] },
          { name: "Gallery", description: null, position: 4, children: [] },
          { name: "Hand painted", description: null, position: 5, children: [] },
          { name: "Jazz", description: null, position: 6, children: [] },
          { name: "Lyrical", description: null, position: 7, children: [] },
          { name: "Modern", description: null, position: 8, children: [] },
          { name: "Other", description: null, position: 9, children: [] },
          { name: "Pancake tutus", description: null, position: 10, children: [] },
          { name: "Stretch", description: null, position: 11, children: [] },
          { name: "Tap", description: null, position: 12, children: [] },
        ],
      },
    ],
  },
  {
    name: "Pageant Wear",
    description: null,
    position: 2,
    children: [
      { name: "Casual wear", description: null, position: 0, children: [] },
      { name: "Glitz dresses", description: null, position: 1, children: [] },
      { name: "Natural dresses", description: null, position: 2, children: [] },
      { name: "OOC/fun fashion", description: null, position: 3, children: [] },
      { name: "Swimwear", description: null, position: 4, children: [] },
    ],
  },
];

interface CategoryData {
  name: string;
  description: string | null;
  position: number;
  children: CategoryData[];
}

/**
 * Recursively seeds categories with parent-child relationships
 * IDs are auto-generated by the database
 */
async function seedCategoriesRecursive(
  items: CategoryData[],
  parentId?: string,
) {
  for (const item of items) {
    // Find existing category by both name AND parentId
    const existing = await prisma.category.findFirst({
      where: { name: item.name, parentId },
    });

    let categoryId: string;

    if (existing) {
      categoryId = existing.id;
      // Update position if different
      if (existing.position !== item.position) {
        await prisma.category.update({
          where: { id: existing.id },
          data: { position: item.position },
        });
        console.log(`✓ Updated position for: ${item.name}`);
      } else {
        console.log(`ℹ Category already exists: ${item.name}`);
      }
    } else {
      const category = await prisma.category.create({
        data: {
          name: item.name,
          description: item.description,
          position: item.position,
          parentId,
        },
      });
      categoryId = category.id;
      console.log(
        `✓ Created category: ${item.name}${parentId ? ` (parent: ${parentId})` : " (root level)"}`,
      );
    }

    if (item.children && item.children.length > 0) {
      await seedCategoriesRecursive(item.children, categoryId);
    }
  }
}

async function seed() {
  console.log("🌱 Seeding categories from database export...\n");

  try {
    await seedCategoriesRecursive(categories);
    console.log("\n✅ Categories seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding categories:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seed();
