import prisma from "../lib/prisma";

/**
 * Category hierarchy exported from database
 * Auto-generated from export-categories.ts
 *
 * Note: Duplicate names (e.g., "Jazz" under both Figure Skating and Aerial)
 * are intentional and will be created as separate records in the database,
 * each with its own ID and parentId reference to their respective parent.
 */
const categories = [
  {
    name: "Dance wear",
    description: null,
    children: [
      {
        name: "Aerial",
        description: null,
        children: [
          { name: "Accessories", description: null, children: [] },
          { name: "Acro", description: null, children: [] },
          { name: "Airbrush", description: null, children: [] },
          { name: "Character inspired", description: null, children: [] },
          { name: "Gallery", description: null, children: [] },
          { name: "Hand painted", description: null, children: [] },
          { name: "Jazz", description: null, children: [] },
          { name: "Lyrical", description: null, children: [] },
          { name: "Modern", description: null, children: [] },
          { name: "Other", description: null, children: [] },
          { name: "Pancake tutus", description: null, children: [] },
          { name: "Stretch", description: null, children: [] },
          { name: "Tap", description: null, children: [] },
        ],
      },
      {
        name: "Figure Skating",
        description: null,
        children: [
          { name: "Accessories", description: null, children: [] },
          { name: "Acro", description: null, children: [] },
          { name: "Airbrush", description: null, children: [] },
          { name: "Character inspired", description: null, children: [] },
          { name: "Gallery", description: null, children: [] },
          { name: "Hand painted", description: null, children: [] },
          { name: "Jazz", description: null, children: [] },
          { name: "Lyrical", description: null, children: [] },
          { name: "Modern", description: null, children: [] },
          { name: "Other", description: null, children: [] },
          { name: "Pancake tutus", description: null, children: [] },
          { name: "Stretch", description: null, children: [] },
          { name: "Tap", description: null, children: [] },
        ],
      },
    ],
  },
  {
    name: "Pageant Wear",
    description: null,
    children: [
      { name: "Casual wear", description: null, children: [] },
      { name: "Glitz dresses", description: null, children: [] },
      { name: "Natural dresses", description: null, children: [] },
      { name: "OOC/fun fashion", description: null, children: [] },
      { name: "Swimwear", description: null, children: [] },
    ],
  },
];

interface CategoryData {
  name: string;
  description: string | null;
  children: CategoryData[];
}

/**
 * Recursively seeds categories with parent-child relationships
 * IDs are auto-generated by the database
 */
async function seedCategoriesRecursive(
  items: CategoryData[],
  parentId?: string
) {
  for (const item of items) {
    // Find existing category by both name AND parentId
    const existing = await prisma.category.findFirst({
      where: { name: item.name, parentId },
    });

    let categoryId: string;

    if (existing) {
      categoryId = existing.id;
      console.log(`ℹ Category already exists: ${item.name}`);
    } else {
      const category = await prisma.category.create({
        data: {
          name: item.name,
          description: item.description,
          parentId,
        },
      });
      categoryId = category.id;
      console.log(
        `✓ Created category: ${item.name}${parentId ? ` (parent: ${parentId})` : " (root level)"}`
      );
    }

    if (item.children && item.children.length > 0) {
      await seedCategoriesRecursive(item.children, categoryId);
    }
  }
}

async function seed() {
  console.log("🌱 Seeding categories from database export...\n");

  try {
    await seedCategoriesRecursive(categories);
    console.log("\n✅ Categories seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding categories:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seed();
